#!/usr/bin/env python3
"""Generates docs/standards.md from docs/standards.toml.

The overview is a table with merged cells – component, then each standard of
it, then one row per check – which Markdown cannot express. Written by hand
as HTML, every new check would mean recounting rowspans; kept as data it is
one more [[component.standard.review]] entry. run_tests.sh runs `--check` so
the generated page never drifts from the data.

    python3 tools/standards.py          # write docs/standards.md
    python3 tools/standards.py --check  # exit 1 if it is out of date
"""
from __future__ import annotations

import html
import os
import sys
import tomllib

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC = os.path.join(ROOT, "docs", "standards.toml")
OUT = os.path.join(ROOT, "docs", "standards.md")


def esc(s: str) -> str:
    return html.escape(s, quote=False)


def render(data: dict) -> str:
    reviews = {r["id"]: r for r in data.get("reviews", [])}
    out = [
        "<!-- Generated by tools/standards.py from standards.toml – do not edit. -->",
        "# Standards and checks",
        "",
        "Which component follows which standard, and when it was last checked "
        "against it. Edit [`standards.toml`](standards.toml) and run "
        "`python3 tools/standards.py`; `tests/run_tests.sh` fails when this page "
        "is not current.",
        "",
        "A **check** means the standard's text was read next to the code. *Basis* "
        "is what the code was written or verified against when it was written; "
        "**tbd** means no check is recorded yet.",
        "",
        "## Check log",
        "",
    ]
    if reviews:
        out += ["| ID | Date | Kind | By | Checked | Fixed in |",
                "|---|---|---|---|---|---|"]
        for r in data["reviews"]:
            out.append(
                f'| <a id="{r["id"].lower()}"></a>{r["id"]} | {r["date"]} | {r["kind"]} | '
                f'{r["by"]} | `{r["reviewed"]}` | `{r.get("fixed", "")}` |'
            )
    else:
        out.append("No check recorded yet.")
    out += [
        "",
        "## Components",
        "",
        "<table>",
        "<thead><tr><th>Component</th><th>Standard</th><th>Basis</th><th>Sections</th>"
        "<th>Last check</th><th>Result</th><th>Open</th></tr></thead>",
    ]
    for c in data["component"]:
        rows = sum(max(1, len(s.get("review", []))) for s in c["standard"])
        out.append("<tbody>")
        first_c = True
        for s in c["standard"]:
            revs = s.get("review", []) or [{"review": "tbd"}]
            first_s = True
            for rv in revs:
                cells = []
                if first_c:
                    cells.append(f'<td rowspan="{rows}"><b>{esc(c["name"])}</b><br>'
                                 f'<code>{esc(c["code"])}</code></td>')
                if first_s:
                    n = len(revs)
                    cells.append(f'<td rowspan="{n}">{esc(s["name"])}</td>')
                    cells.append(f'<td rowspan="{n}">{esc(s.get("basis", ""))}</td>')
                    cells.append(f'<td rowspan="{n}">{esc(s.get("sections", ""))}</td>')
                rid = rv.get("review", "tbd")
                if rid == "tbd":
                    cells.append("<td>tbd</td>")
                else:
                    if rid not in reviews:
                        raise SystemExit(f"standards.toml: unknown review {rid!r} in {c['name']}")
                    r = reviews[rid]
                    cells.append(f'<td><a href="#{rid.lower()}">{rid}</a> {r["date"]}</td>')
                cells.append(f'<td>{esc(rv.get("result", ""))}</td>')
                cells.append(f'<td>{esc(rv.get("open", ""))}</td>')
                out.append("<tr>" + "".join(cells) + "</tr>")
                first_c = first_s = False
        out.append("</tbody>")
    out += ["</table>", ""]
    return "\n".join(out)


def main() -> int:
    with open(SRC, "rb") as f:
        text = render(tomllib.load(f))
    if "--check" in sys.argv[1:]:
        try:
            with open(OUT) as f:
                current = f.read()
        except FileNotFoundError:
            current = ""
        if current != text:
            print("docs/standards.md is out of date – run python3 tools/standards.py")
            return 1
        print(f"checked docs/standards.md: current ({text.count('<td>tbd</td>')} standards without a recorded check)")
        return 0
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote docs/standards.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
